before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  ldflags:
  - "-X 'github.com/radiorabe/virtual-saemubox/cmd.version={{ .Tag }}'"
  - "-X 'github.com/radiorabe/virtual-saemubox/cmd.commit={{ .FullCommit }}'"
  - "-X 'github.com/radiorabe/virtual-saemubox/cmd.date={{.Date}}'"
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
dockers:
  - image_templates:
      - "docker.pkg.github.com/radiorabe/virtual-saemubox/virtual-saemubox:{{ .Tag }}"
      - "docker.pkg.github.com/radiorabe/virtual-saemubox/virtual-saemubox:v{{ .Major }}"
      - "docker.pkg.github.com/radiorabe/virtual-saemubox/virtual-saemubox:v{{ .Major }}.{{ .Minor }}"
      - "docker.pkg.github.com/radiorabe/virtual-saemubox/virtual-saemubox:latest"
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
    extra_files:
      - etc/passwd
