name: Lint and Test

on:
  push:
    branches-ignore:
      - master
      - main
      - gh-pages

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19.x

      - name: Run GolangCI-Lint
        uses: golangci/golangci-lint-action@v5.3.0
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19.x

      - run: go test ./...
