name: Run pre-commit

on:
  push:
    branches-ignore:
      - master
      - main
      - gh-pages

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Python
        uses: actions/setup-python@v2.3.0

      - name: Run pre-commit
        uses: pre-commit/action@v2.0.3
