name: goreleaser

on:
  release:
    types:
      - created

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Unshallow Clone
        run: git fetch --prune --unshallow

      - name: Set up Go
        uses: actions/setup-go@v2.1.5
        with:
          go-version: 1.15.x

      - name: Login to GitHub Package Registry
        run: echo "${{ secrets.GH_PAT_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2.8.1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
