
name: Run semantic-release

on:
  push:
    branches:
      - master
      - main

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unshallow Clone
        run: git fetch --prune --unshallow

      - name: Run go-semantic-release
        id: semrel
        uses: go-semantic-release/action@v1.23
        with:
          github-token: ${{ secrets.GH_PAT_TOKEN }}
          allow-initial-deployment-versions: true
